### ISSUE TITLE
NUCLEO_F429ZI : ARM, GCC_ARM toolchains, Benchmark app freezes.

### ISSUE THREAD

**Issue by ashok-rao** [ARMmbed/oob-mbed-os-example-tls#4] opened 2016-10-10 17:01 UTC
Steps to reproduce:
$> mbed compile -t ARM -m NUCLEO_F429ZI

Program execution "freezes" at ECDSA-secp256r1 even after leaving it aside for >10mins. Screenshot below.

![nucleo_f429zi_benchmark_arm_silent_crash](https://cloud.githubusercontent.com/assets/17567812/19244280/83b5ffbe-8f13-11e6-9cb5-f8b7749ac4cf.jpg)

**Comment by ashok-rao** [comment] 2016-10-10 17:09
Issue occurs with GCC_ARM too. With GCC_ARM, it "freezes" at ECDSA-secp384r1. Screenshot below.

![nucleo_f429zi_benchmark_gcc_silent_crash](https://cloud.githubusercontent.com/assets/17567812/19244538/a5977e54-8f14-11e6-86c0-830a916c0328.jpg)

**Comment by 0xc0170** [comment] 2016-10-11 10:50
cc @andresag01 @yanesca @sbutcher-arm

**Comment by sbutcher-arm** [comment] 2016-10-11 10:57
This is a duplicate of [mbed OS example TLS issue #15](https://github.com/ARMmbed/mbed-os-example-tls/issues/15), and is fixed by [PR #16](https://github.com/ARMmbed/mbed-os-example-tls/pull/16), which is pending merge.

**Comment by andresag01** [comment] 2016-10-14 08:38
PR fixes this issue https://github.com/ARMmbed/oob-mbed-os-example-tls/pull/11

**Closed by andresag01** 2016-10-14 08:38 UTC
