### ISSUE TITLE
[NUCLEO_F429ZI] tls-client ARM build handshake fails (RC3)

### ISSUE THREAD

**Issue by toyowata** [ARMmbed/oob-mbed-os-example-tls#15] opened 2016-10-17 05:52 UTC
### Step to reproduce

```
mbed import https://github.com/ARMmbed/oob-mbed-os-example-tls
cd oob-mbed-os-example-tls\tls-client
mbed compile -m NUCLEO_F429ZI -t ARM
```

### Runtime error log

```
Using Ethernet LWIP
Client IP Address is 172.27.37.254
Connecting with developer.mbed.org
Starting the TLS handshake...
mbedtls_ssl_handshake() failed: -0x0001 (-1): UNKNOWN ERROR CODE (0001)
MBED: Socket Error: -1
```

**Comment by MarceloSalazar** [comment] 2016-10-17 07:10
@sbutcher-arm

**Comment by ashok-rao** [comment] 2016-10-17 15:46
I can reproduce this too. However, using "mbed import" produces the same result as seen by @toyowata and using "git clone" produces the following error:
(using the latest commit of mbed-os)
```
C:\TLS2\oob-mbed-os-example-tls\tls-client>more mbed-os.lib
https://github.com/ARMmbed/mbed-os/#873686ce791c7db1697519d3716c6b9a193e21b5
```
![tls](https://cloud.githubusercontent.com/assets/17567812/19444603/01fa8118-9489-11e6-8a01-49467876cc01.jpg)

**Comment by MarceloSalazar** [comment] 2016-10-17 15:48
@sbutcher-arm @andresag01 please have a look

**Comment by ashok-rao** [comment] 2016-10-17 15:54
P.S: Using ARM compiler, the error code is different too. Please see below.
```
Using Ethernet LWIP
Client IP Address is 10.2.202.51
Connecting with developer.mbed.org
Starting the TLS handshake...
RTX error code: 0x00000001, task ID: 0x2000DEE0
```

**Comment by andresag01** [comment] 2016-10-17 16:22
I am also able to reproduce this issue. It seems that the problem is the same as in https://github.com/ARMmbed/oob-mbed-os-example-tls/issues/17

**Comment by andresag01** [comment] 2016-10-18 12:32
This issue is fixed by https://github.com/ARMmbed/oob-mbed-os-example-tls/pull/18

**Closed by andresag01** 2016-10-18 12:32 UTC
